create database bikestoreproject;

use bikestoreproject;

show tables; 

select * from brands;
select * from categories; 
select * from customers; 
select * from order_items; 
select * from orders; 
select * from products; 
select * from staffs; 
select * from stocks;
select * from stores;

-- Store Performance – Total revenue generated by each store 
select s.store_name, sum(oi.quantity * oi.list_price) as total_revenue
from stores s 
join orders o 
on s.store_id = o.store_id
join order_items oi 
on o.order_id = oi.order_id 
group by s.store_name 
order by total_revenue asc;


-- 2. Product Popularity – Top 5 most sold products by quantity.
select p.product_name , sum(oi.quantity) as total_sold 
from order_items oi 
join products p 
on oi.product_id = p.product_id
group by p.product_name 
order by total_sold desc
limit 5;

-- 3. Customer Location – Customers who placed orders with store names.
SELECT c.first_name, c.last_name, c.city, s.store_name FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN stores s
ON o.store_id = s.store_id;

-- Brand Insights – Total number of products per brand.
select b.brand_name, count(p.product_id) as Total_number 
from brands b 
join products p 
on b.brand_id = p.brand_id 
group by b.brand_name 
order by total_number desc;

-- Low Stock Alert – Products with zero quantity in stock.
select p.product_name, s.quantity from stocks s 
join products p 
on s.product_id = p.product_id 
where s.quantity = 0;





